version: '3.8'

services:
  backend:
    build:
      context: ./inv_backend
    container_name: inv-backend
    ports:
      - "5000:5000"
    env_file:
      - ./inv_backend/.env
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./inv_frontend
    container_name: inv-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
